USE [master]
GO
/****** Object:  Database [Privilege ]    Script Date: 2015/6/4 22:32:02 ******/
CREATE DATABASE [Privilege ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Privilege', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Privilege .mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Privilege _log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Privilege _log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Privilege ] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Privilege ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Privilege ] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Privilege ] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Privilege ] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Privilege ] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Privilege ] SET ARITHABORT OFF 
GO
ALTER DATABASE [Privilege ] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Privilege ] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Privilege ] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Privilege ] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Privilege ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Privilege ] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Privilege ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Privilege ] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Privilege ] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Privilege ] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Privilege ] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Privilege ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Privilege ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Privilege ] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Privilege ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Privilege ] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Privilege ] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Privilege ] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Privilege ] SET RECOVERY FULL 
GO
ALTER DATABASE [Privilege ] SET  MULTI_USER 
GO
ALTER DATABASE [Privilege ] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Privilege ] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Privilege ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Privilege ] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Privilege ', N'ON'
GO
USE [Privilege ]
GO
/****** Object:  Table [dbo].[User]    Script Date: 2015/6/4 22:32:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](250) NOT NULL,
	[Password] [nvarchar](250) NOT NULL,
	[CreateTime] [datetime] NOT NULL,
	[Email] [varchar](256) NOT NULL,
	[isVerify] [bit] NOT NULL,
 CONSTRAINT [PK_USERSINFO] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[UserFunctionality]    Script Date: 2015/6/4 22:32:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[UserFunctionality](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](64) NOT NULL,
 CONSTRAINT [PK_UserFunctionality] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[UserPermission]    Script Date: 2015/6/4 22:32:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserPermission](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UserRoleId] [int] NOT NULL,
	[FunctionalityId] [int] NOT NULL,
 CONSTRAINT [PK_UserPermission] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[UserRole]    Script Date: 2015/6/4 22:32:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserRole](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[RoleName] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK_UserRole] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[UserToUserRole]    Script Date: 2015/6/4 22:32:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserToUserRole](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserRoleId] [int] NOT NULL,
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_UserToUserRole] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[UserPermission]  WITH CHECK ADD  CONSTRAINT [FK_UserPermission_Functionality] FOREIGN KEY([FunctionalityId])
REFERENCES [dbo].[UserFunctionality] ([Id])
GO
ALTER TABLE [dbo].[UserPermission] CHECK CONSTRAINT [FK_UserPermission_Functionality]
GO
ALTER TABLE [dbo].[UserPermission]  WITH CHECK ADD  CONSTRAINT [FK_UserPermission_UserRole] FOREIGN KEY([UserRoleId])
REFERENCES [dbo].[UserRole] ([ID])
GO
ALTER TABLE [dbo].[UserPermission] CHECK CONSTRAINT [FK_UserPermission_UserRole]
GO
ALTER TABLE [dbo].[UserToUserRole]  WITH CHECK ADD  CONSTRAINT [FK_UserToUserRole_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[UserToUserRole] CHECK CONSTRAINT [FK_UserToUserRole_User]
GO
ALTER TABLE [dbo].[UserToUserRole]  WITH CHECK ADD  CONSTRAINT [FK_UserToUserRole_UserRole] FOREIGN KEY([UserRoleId])
REFERENCES [dbo].[UserRole] ([ID])
GO
ALTER TABLE [dbo].[UserToUserRole] CHECK CONSTRAINT [FK_UserToUserRole_UserRole]
GO
USE [master]
GO
ALTER DATABASE [Privilege ] SET  READ_WRITE 
GO
